# Generated by Django 4.2.7 on 2025-04-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('pickup', '取件'), ('transit', '运输'), ('transfer', '中转'), ('delivery', '派送'), ('delivered', '送达')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '物流记录',
                'verbose_name_plural': '物流记录',
                'ordering': ['-timestamp'],
            },
        ),
    ]
