# Generated by Django 4.2.7 on 2025-04-12 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_alter_shipment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsrecord',
            name='description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='logisticsrecord',
            name='event_type',
            field=models.CharField(choices=[('pickup', '取件'), ('transit', '运输'), ('transfer', '中转'), ('delivery', '派送'), ('delivered', '送达')], max_length=20, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='logisticsrecord',
            name='handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handled_records', to=settings.AUTH_USER_MODEL, verbose_name='处理人员'),
        ),
        migrations.AlterField(
            model_name='logisticsrecord',
            name='location',
            field=models.CharField(max_length=100, verbose_name='地点'),
        ),
        migrations.AlterField(
            model_name='logisticsrecord',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_records', to='shipments.shipment', verbose_name='快递单'),
        ),
        migrations.AlterField(
            model_name='logisticsrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间戳'),
        ),
        migrations.AddIndex(
            model_name='logisticsrecord',
            index=models.Index(fields=['-timestamp'], name='logistics_l_timesta_81590e_idx'),
        ),
        migrations.AddIndex(
            model_name='logisticsrecord',
            index=models.Index(fields=['event_type'], name='logistics_l_event_t_141944_idx'),
        ),
    ]
