# Generated by Django 4.2.7 on 2025-04-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('picked_up', '已取件'), ('in_transit', '运输中'), ('delivered', '已送达'), ('completed', '已完成')], default='pending', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('pickup_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '快递单',
                'verbose_name_plural': '快递单',
                'ordering': ['-created_at'],
            },
        ),
    ]
