# Generated by Django 4.2.7 on 2025-04-12 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='delivery_address',
            field=models.TextField(verbose_name='送达地址'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='description',
            field=models.TextField(verbose_name='包裹描述'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预计送达时间'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pickup_address',
            field=models.TextField(verbose_name='取件地址'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shipments', to=settings.AUTH_USER_MODEL, verbose_name='收件人'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_shipments', to=settings.AUTH_USER_MODEL, verbose_name='发件人'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('picked_up', '已取件'), ('in_transit', '运输中'), ('delivered', '已送达'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='运单号'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='重量(kg)'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='shipments_s_trackin_80db53_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipments_s_status_536511_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['created_at'], name='shipments_s_created_1bef45_idx'),
        ),
    ]
